sudo: required

language: java

jdk:
  - openjdk8

services:
  - docker

cache:
  yarn: true
  directories:
    - $HOME/.m2
    - $HOME/.cache/yarn

env:
  global:
    - NODE_VERSION="10.16.0"
    # AWS_ACCESS_KEY_ID
    - secure: "hIF3fVqQdkYEDoFkdac1oNxkcbCli/ZBWF2g54aiWJ+Zv7bMFl4zxBcZPnFycr9ezEJaTyAw8Y2G1RoWnkeFmwLr5fMYJwAG21g/UXJlxBfTUaq/9FBt2622J3Ybm4xtfMesl0HCtH2hpxoNfuV3SUti7K2QPJm3NU10apYOOo4="
    # AWS_SECRET_ACCESS_KEY
    - secure: "sx9CgjvVJSkVTVCh4b7VFyaUc4mpoK+Sh1cWjZBLiaCJ8PNCzOamFdzPzBGCPBUjgzdyYeIZCQUi+3i7CG/iZGt8OKQqbIh7iRpWz8jUrJ+iULZN1mGx+JfffU18SfDZXdRbHmpiVjizFUqEhXpEjzznm34bn17lN1jg/foulDM="

before_install:
  - nvm install $NODE_VERSION

install:
  - git clone --recurse-submodules --depth 1 ${EPERUSTEET_UI_BRANCH} https://github.com/Opetushallitus/eperusteet-ui.git
  - git clone https://github.com/Opetushallitus/ci-tools.git
  - source ci-tools/common/setup-tools.sh
  - export ARTIFACT_NAME="eperusteet"

script:
  # Rakennetaan uusi UI
  - export EPERUSTEET_SERVICE_DIR=$TRAVIS_BUILD_DIR/eperusteet/eperusteet-service
  - cd eperusteet-ui
  - yarn install --silent
  - cd eperusteet-frontend-utils/vue
  - yarn install --silent
  - yarn gen:api:eperusteet
  - rm -rf node_modules
  - cd ../..
  - git rev-parse HEAD
  - yarn run build
  - cd ..


  - cd ${ARTIFACT_NAME}

  - mvn clean install -B -Dbranch=${TRAVIS_BRANCH} -Drevision=${TRAVIS_COMMIT} -DbuildNumber=${TRAVIS_BUILD_NUMBER}

  - mv ${ARTIFACT_NAME}-service/target/${ARTIFACT_NAME}-service.war $DOCKER_BUILD_DIR/artifact/${ARTIFACT_NAME}-service.war
  - mv ${ARTIFACT_NAME}-app/target/${ARTIFACT_NAME}-app.war $DOCKER_BUILD_DIR/artifact/${ARTIFACT_NAME}-app.war
  - cp -vr src/main/resources/oph-configuration $DOCKER_BUILD_DIR/config/
  - cp -vr src/main/resources/tomcat $DOCKER_BUILD_DIR/config/

  - cd ..

  - export BASE_IMAGE="baseimage-war-tomcat8-openjdk8:master"
  - ./ci-tools/common/pull-image.sh
  - ./ci-tools/build/build-war.sh ${ARTIFACT_NAME}

deploy:
  provider: script
  script: ./ci-tools/build/upload-image.sh ${ARTIFACT_NAME}
  on:
    all_branches: true
