
ALTER TABLE yl_lukioopetuksen_perusteen_sisalto RENAME TO yl_lukiokoulutuksen_perusteen_sisalto;
ALTER TABLE yl_lukioopetuksen_perusteen_sisalto_aud RENAME TO yl_lukiokoulutuksen_perusteen_sisalto_aud;
ALTER TABLE yl_lukioopetuksen_perusteen_sisalto_yl_oppiaine RENAME TO yl_lukiokoulutuksen_perusteen_sisalto_yl_oppiaine;
ALTER TABLE yl_lukioopetuksen_perusteen_sisalto_yl_oppiaine_aud RENAME TO yl_lukiokoulutuksen_perusteen_sisalto_yl_oppiaine_aud;
