ALTER TABLE perusteenosa ADD COLUMN valmis BOOLEAN DEFAULT FALSE;
ALTER TABLE perusteenosa ADD COLUMN kaannettava BOOLEAN DEFAULT FALSE;

ALTER TABLE perusteenosa_aud ADD COLUMN valmis BOOLEAN DEFAULT FALSE;
ALTER TABLE perusteenosa_aud ADD COLUMN kaannettava BOOLEAN DEFAULT FALSE;