ALTER TABLE yl_lukiokoulutuksen_opetuksen_yleiset_tavoitteet ALTER COLUMN otsikko_id DROP NOT NULL;
ALTER TABLE yl_lukiokoulutuksen_opetuksen_yleiset_tavoitteet ALTER COLUMN sisalto_id DROP NOT NULL;
ALTER TABLE yl_lukiokoulutuksen_opetuksen_yleiset_tavoitteet_aud ALTER COLUMN otsikko_id DROP NOT NULL;
ALTER TABLE yl_lukiokoulutuksen_opetuksen_yleiset_tavoitteet_aud ALTER COLUMN sisalto_id DROP NOT NULL;