alter table yl_perusop_perusteen_sisalto_yl_laajaalainen_osaaminen
    rename column laajaalalaisetosaamiset_id to laajaalaisetosaamiset_id;

alter table yl_perusop_perusteen_sisalto_yl_laajaalainen_osaaminen_AUD
   rename column laajaalalaisetosaamiset_id to laajaalaisetosaamiset_id;

