services:
  eperusteet:
    image: postgres:15
    environment:
      POSTGRES_USER: oph
      POSTGRES_PASSWORD: test
      POSTGRES_DB: eperusteet
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - eperusteet_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U oph -d eperusteet"]
      interval: 2s
      timeout: 5s
      retries: 10
      start_period: 5s

volumes:
  eperusteet_data:
