fi.vm.sade.eperusteet.eperusteet.amosaa.service=https://virkailija.testiopintopolku.fi/eperusteet-amosaa-service
fi.vm.sade.eperusteet.eperusteet.ylops.service=https://virkailija.testiopintopolku.fi/eperusteet-ylops-service
lokalisointi.service.url=https://virkailija.testiopintopolku.fi/lokalisointi/cxf/rest/v1/localisation?

eperusteet.export.lampi.enabled=true
eperusteet.export.lampi-bucket=oph-lampi-qa
